version: '3.9'
services:
  frontend:
    build: ./nfc-frontend
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5
    volumes:
      - ./nfc-frontend:/usr/app
    container_name: nfc-frontend
  backend:
    build: ./nfc-node-api
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3002
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=cashforce_v3
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3002"]
      timeout: 10s
      retries: 5
    volumes:
      - ./nfc-node-api:/usr/app
    container_name: nfc-node-api
    networks:
      - app-nfc
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - "3030:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    networks:
      - app-nfc

networks:
  app-nfc:
    driver: bridge